env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - prettier
  - plugin:vue/essential
rules:
  prettier/prettier:
    - off
    - singleQuote: true
      printWidth: 100
  no-console: off
  quotes:
    - error
    - single
    - avoidEscape: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
