env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - prettier
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      printWidth: 100
  no-console: off
  quotes:
    - error
    - single
    - avoidEscape: true
plugins:
  - prettier
